//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pop4.Entities
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Windows.Media;

    public partial class Product
    {
        public string article { get; set; }
        public string name { get; set; }
        public int unit_of_measurement { get; set; }
        public decimal coust { get; set; }
        public int max_discount { get; set; }
        public int manufacturer { get; set; }
        public int supplier { get; set; }
        public int category { get; set; }
        public int current_discount { get; set; }
        public int quantity_in_stock { get; set; }
        public string description { get; set; }
        public byte[] photo { get; set; }
    
        public string AdminVisibiliti
        {
            get 
            {
                if (App.CurrentUser == null)
                {
                    return "Hidden";
                }
                else if (App.CurrentUser.role == 1)
                {
                    return "Hidden";
                }
                return "Visible";
            }
        }


        public string Background_Color
        {
            get
            {
                if (current_discount > 15)
                {
                    return "#7fff00";
                }
                else return Colors.White.ToString();
            }
        }

        public string Cross_out
        {
            get
            {
                if (current_discount > 0)
                {
                    return "Srikethrough";
                }
                else return "None";
            }
        }
        public string Correct_Manufacturer
        {
            get
            {
                return Manufacturer1.name.ToString();
            }
        }

        public byte[] Correct_Photo
        {
            get
            {
                if (photo != null)
                    return photo;
                else return File.ReadAllBytes("../../Resources/picture.png");
            }
        }
        public virtual Category Category1 { get; set; }
        public virtual Manufacturer Manufacturer1 { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
